### ISSUE TITLE
How to choose the topic by using -t ？

### ISSUE THREAD

**Issue by bryantaoli** [biomotion/rosbag-utils#1]
How to choose the topic by using -t ？
![image](https://user-images.githubusercontent.com/30526360/77810473-921aea00-70cf-11ea-98ca-267a6ea205c2.png)

**Comment by biomotion** [comment]
You should specify input and output file before -v argument.

for instance,

```bash
python merge_bag.py output.bag input_bag_1.bag input_bag_2.bag -v -t /topic_1 /topic_2
```
